print_info() {
    prin " "
    prin "${c1} 🚀 Sistema"
    info "${c5} ├─ 🐧 OS" distro
    info "${c5} ├─ ⚙️ Kernel" kernel
    info "${c5} ├─ 📦 Paquetes" packages
    info "${c5} └─ ⏱️ Uptime" uptime
    prin " "
    prin "${c1} 💻 Entorno"
    info "${c5} ├─ 👾 Shell" shell
    info "${c5} ├─ 🖥️ Terminal" term
    info "${c5} ├─ 🧠 RAM" memory
    info "${c5} └─ 💾 Disco" disk
    prin " "
    prin "    $(color 1)⬤ $(color 2)⬤ $(color 3)⬤ $(color 4)⬤ $(color 5)⬤ $(color 6)⬤"
}

whoami=$(whoami)
kernel_shorthand="on"
distro_shorthand="off"
os_arch="off"
uptime_shorthand="on"
memory_percent="on"
memory_unit="mib"
package_managers="tiny"
disk_show=('/')
disk_subtitle="dir"
shell_path="off"
shell_version="on"
refresh_rate="off"
de_version="on"
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="─"
separator=" "
block_range=(0 7)
color_blocks="off"
block_width=3
block_height=1
col_offset="auto"
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="ascii"
image_source="${HOME}/.config/neofetch/ascii.txt"
ascii_distro="arch_small"
ascii_colors=(distro)
ascii_bold="on"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=5
yoffset=0
xoffset=0
background_color=
stdout="off"